# Generated by Django 3.0.3 on 2020-02-28 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=200)),
                ('test_content', models.TextField()),
                ('test_published', models.DateTimeField(default=datetime.datetime.now, verbose_name='published at')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
